"""initial

Revision ID: 4965b9e716b8
Revises: 
Create Date: 2022-11-24 00:44:34.345962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4965b9e716b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.INTEGER(), nullable=False),
    sa.Column('port', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('status_services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_service', sa.INTEGER(), nullable=True),
    sa.Column('status_code', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_service'], ['services.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_service'),
    sa.UniqueConstraint('status_code')
    )
    op.create_table('url_services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_service', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['id_service'], ['services.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_service'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_services')
    op.drop_table('status_services')
    op.drop_table('services')
    # ### end Alembic commands ###
