"""initial

Revision ID: 72829ab3d9da
Revises: 
Create Date: 2022-11-22 14:59:39.424913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72829ab3d9da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fast_api_auto_generate_services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.INTEGER(), nullable=False),
    sa.Column('port', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fast_api_auto_generate_services')
    # ### end Alembic commands ###
