"""initial

Revision ID: e64bda4d9b6b
Revises: 
Create Date: 2022-11-24 17:22:28.314958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64bda4d9b6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.TEXT(), nullable=False),
    sa.Column('port', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('status_services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_service', sa.INTEGER(), nullable=True),
    sa.Column('status_code', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_service'], ['services.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_service')
    )
    op.create_table('url_services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_service', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['id_service'], ['services.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_service'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_services')
    op.drop_table('status_services')
    op.drop_table('services')
    # ### end Alembic commands ###
