"""initial

Revision ID: 239ac7daedc7
Revises: b462f70d947f
Create Date: 2023-02-28 01:56:31.995973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239ac7daedc7'
down_revision = 'b462f70d947f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('delete', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'delete')
    # ### end Alembic commands ###
